### PR TITLE
LPS-141137 Disable headless wrapping transaction through header

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]
Hi Edu!

I think is perfect. Custom header and clean logic localized in a concrete place in the TransactionContainerRequestFilter.

Thank you for taking care of it! 🙂

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
