### PR TITLE
LPS-105380 YMLDefinitionOrderCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
Hey @javierdearcos
I fixed SF logic and ran `buildREST`, can you help to check thes last three commits?
https://github.com/javierdearcos/liferay-portal/pull/38/commits/0f1a7c1f08c14899cecb3deab4c1620044ccca05
https://github.com/javierdearcos/liferay-portal/pull/38/commits/3ab359b467e7640c5140d7a7288765d39fa26f1a
https://github.com/javierdearcos/liferay-portal/pull/38/commits/ff54941ef10f41fbabbabfd96ef8fc2b5151e443


/cc @hhuijser

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
I ran `buildREST` in all APIs on my end, only Headless Delivery is affected.

**Comment by javierdearcos** [comment]
Great. Thank you very much for all your work 🙂 

I will wait to check the test results and forward the PR if everything is green

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hey @javierdearcos I have to close this pull, because https://github.com/javierdearcos/liferay-portal/pull/38/commits/814f27a2aa4a29f92ca100126fa8b7b54ab64bae is fixed in [this pull](https://github.com/brianchandotcom/liferay-portal/pull/101961) in different way.

I will resend this pull to Hugo later.

Thanks.

**Comment by ling-alan-huang** [comment]
Resent: https://github.com/hhuijser/liferay-portal/pull/5566

**Comment by javierdearcos** [comment]
Thank you!

**Pull request closed without merging**
