### PR TITLE
LPS-111138 Fix errors in GraphQL autogenerated tests

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:forward

**Comment by jpince** [comment]
@javierdearcos I recommend just sending this directly to Brain Chan (ci:reopen the pull after it auto-closes) since it is urgent. And just make sure the workflow team (inacionery and barrosdennys) knows about about the test failures here, since they will either be introduced to upstream or are flaky tests. They can work with Leo to figure out what to do next.

**Comment by manoelcyreno** [comment]
ci:test:headless-acceptance

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
@jpince Thank you Jason. I'll do it like that

**Pull request closed without merging**
