### PR TITLE
LPS-106886 Create and modify i18n properties in one request in Headless Delivery

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:forward

**Pull request closed without merging**
