### PR TITLE
LPS-105232 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by lawrence-lee**
What do you think about these two changes? We don't have to keep them. I think they would help with future maintenance.

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by javierdearcos** [comment]
> What do you think about these two changes? We don't have to keep them. I think they would help with future maintenance.

Sure! I found it perfect. Furthermore, you are the expert here 😉 

Thanks!

**Comment by javierdearcos** [comment]
If ```ci:test:project-templates``` passes, do you thinks it's ok to run `ci:forward` from here to merged it in master as it is right now @lawrence-lee?

**Comment by lawrence-lee** [comment]
if it passes, I will send it to Peter for review since its a new template

**Comment by javierdearcos** [comment]
ok, great. I'll wait to feedback then

**Pull request closed without merging**
